Revert "semi clean"
This reverts commit 480dbbace4115334d5f05a15b7bb1a88b7037571.

diff --git a/.github/workflows/snapshot-ci.yml b/.github/workflows/snapshot-ci.yml
--- a/.github/workflows/snapshot-ci.yml
+++ b/.github/workflows/snapshot-ci.yml
@@ -49,12 +49,16 @@ jobs:
           fi
           echo "SCRIPTS_PATH=$SCRIPTS_PATH" >> $GITHUB_ENV  
 
-      - name: Checkout script
+      - name: Checkout repo
         uses: actions/checkout@v4
-        with:
-          sparse-checkout: |
-            .github
-          sparse-checkout-cone-mode: false
+
+      - name: Inspect script dir
+        run: |
+          echo "What is scripts?"
+          file ${GITHUB_WORKSPACE}/.github/workflows/scripts || echo "scripts does not exist"
+          
+          echo "Listing contents"
+          ls -al ${GITHUB_WORKSPACE}/.github/workflows/scripts || echo "Cannot list contents"
 
       - name: Confirm script is present
         run: |
@@ -64,6 +68,7 @@ jobs:
 
       - name: Checking for powsybl-core snapshot branch
         run: ${{ env.SCRIPTS_PATH }}/check_snapshot_branch.sh "https://github.com/powsybl/powsybl-open-loadflow.git" ${{ env.CORE_VERSION }}
+
 
       - name: Checkout core sources
         uses: actions/checkout@v4
