correct path ?
Signed-off-by: CHEN Roxane <roxane.chen@rte-france.com>

diff --git a/.github/workflows/snapshot-ci.yml b/.github/workflows/snapshot-ci.yml
--- a/.github/workflows/snapshot-ci.yml
+++ b/.github/workflows/snapshot-ci.yml
@@ -66,7 +66,9 @@ jobs:
           path: scripts
 
       - name: Confirm script is present
-        run: test -f "${{ env.SCRIPTS_PATH }}/check_snapshot_branch.sh" && echo "Script OK" || echo "Script MISSING"
+        run: |
+          ls -l ${GITHUB_WORKSPACE}
+          test -f "${{ env.SCRIPTS_PATH }}/check_snapshot_branch.sh" && echo "Script OK" || echo "Script MISSING"
 
       - name: Checking for powsybl-open-loadflow snapshot branch
         run: ${{ env.SCRIPTS_PATH }}/check_snapshot_branch.sh "https://github.com/powsybl/powsybl-open-loadflow.git" ${{ env.CORE_VERSION }}
